### ISSUE TITLE
New consensus genomes

### ISSUE THREAD

**Issue by trvrb** [blab/zika-usvi#2]
@alliblk --- Can you copy the new USVI consensus genomes that are in `blab/zika-seq` over here? I like having public sequences on Nextstrain point to this repo. We should also update the bioRxiv paper. Include a data table etc... First pass at things as we're getting the full analysis together.

**Comment by trvrb** [comment]
Looks like this was resolved in 576b948b0044f8ab5d58d3585f7676c721f539ef?

**Comment by alliblk** [comment]
Yes. I'll close the issue.
